<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_login_logo</name>
   <tag></tag>
   <elementGuidId>a362dd9c-d7b1-4034-9ea2-e76a33a5d19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.login_logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>247aab47-ee79-4319-8f54-f2311e9780b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login_logo</value>
      <webElementGuid>f5ed4113-aa92-469d-95b5-1e547829f0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/div[@class=&quot;login_logo&quot;]</value>
      <webElementGuid>17af9155-d582-488d-aa9a-2cf9ca524d1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>a9a8790f-1312-4b43-827f-010f1f9b43c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
