<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bot_column</name>
   <tag></tag>
   <elementGuidId>c213f0b1-20d1-4bd7-98bf-75a2ffece4dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.bot_column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eec5bf82-82e2-4eb5-8825-173c6df902c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bot_column</value>
      <webElementGuid>866aef5d-4e97-42ad-ba85-0fd1ec015551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/Login_Bot_graphic.png</value>
      <webElementGuid>0ec77f20-5600-47f3-965f-0baef5e63e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/div[@class=&quot;login_wrapper&quot;]/div[@class=&quot;login_wrapper-inner&quot;]/img[@class=&quot;bot_column&quot;]</value>
      <webElementGuid>b187974c-6e17-49aa-a12c-ad9f46595e14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1324a75e-6e1c-4ab4-bcb0-600a644866a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/Login_Bot_graphic.png']</value>
      <webElementGuid>20c65596-84e0-46f8-a365-6c6d25c5a3f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
