<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Twitter</name>
   <tag></tag>
   <elementGuidId>fecebcfd-447b-4b90-8c55-78d5f0a0852e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.social_twitter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f74e27ef-b91e-4ce4-ae0c-9c80dcc8de46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>social_twitter</value>
      <webElementGuid>920fbefd-aab0-4437-b55f-5a4d1492b266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Twitter</value>
      <webElementGuid>38ac5cd6-39e9-4d6d-a658-1da2b69f75a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/footer[@class=&quot;footer&quot;]/ul[@class=&quot;social&quot;]/li[@class=&quot;social_twitter&quot;]</value>
      <webElementGuid>ebbb2bde-7a03-4946-9e42-bcb9d00e4dab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>7f43192c-b908-469c-9550-f06590629648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Twitter' or . = 'Twitter')]</value>
      <webElementGuid>f1710ce1-cc5b-4cf2-b3df-a369c5225e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
