<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_peek</name>
   <tag></tag>
   <elementGuidId>22d0e18e-2d57-426b-8a37-a18fd9f58baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.peek</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inventory_container']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07846485-dab3-4241-bb31-38fa71fcc52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peek</value>
      <webElementGuid>b68bc70f-0687-4575-9b7b-8ca4ca5c7759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contents_wrapper&quot;)/div[@id=&quot;inventory_container&quot;]/div[1]/div[@class=&quot;header_secondary_container&quot;]/div[@class=&quot;peek&quot;]</value>
      <webElementGuid>3ed105c8-5d77-47bf-b3ce-b0c4476c09df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory_container']/div/div/div</value>
      <webElementGuid>3c6386a8-9eb8-44ec-a898-7ffa8df71068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>d32725ed-80c9-46bc-b31d-1a9a2e1bbe21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
