<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CANCEL</name>
   <tag></tag>
   <elementGuidId>7b31f4ca-611f-45f0-abbc-5591d6d92f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_info_container']/div/form/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cart_cancel_link.btn_secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1d5d585-9cfd-4c63-bb19-008ef192b9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_cancel_link btn_secondary</value>
      <webElementGuid>2a4ece2f-a3fb-4431-be6e-6ae34a266d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./cart.html</value>
      <webElementGuid>9e6fdbef-478c-4bc8-8324-0c3490358278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL</value>
      <webElementGuid>7f0e0520-3bb9-4c95-87f5-db6aed4ed7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_info_container&quot;)/div[@class=&quot;checkout_info_wrapper&quot;]/form[1]/div[@class=&quot;checkout_buttons&quot;]/a[@class=&quot;cart_cancel_link btn_secondary&quot;]</value>
      <webElementGuid>eba0d8f8-e11a-46e9-a1cb-3a78f871f7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout_info_container']/div/form/div[2]/a</value>
      <webElementGuid>b2a0e702-d72d-40f5-b4a1-169091560da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CANCEL')]</value>
      <webElementGuid>97a3d079-0fde-4db7-91c8-0d7389359c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, './cart.html')])[2]</value>
      <webElementGuid>4a09bd9c-bff3-4b75-b267-4d4e5d8b00ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>2439c818-9aef-4293-b3a4-4384b995467b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './cart.html' and (text() = 'CANCEL' or . = 'CANCEL')]</value>
      <webElementGuid>159bfe0c-de5c-451a-ab76-52153df5d105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
