<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divlogin_button_container</name>
   <tag></tag>
   <elementGuidId>78dbb43f-24f4-47a0-bf8a-40ca2518efa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_button_container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_button_container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7511a46e-b8f6-49ce-9d18-948b39061c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_button_container</value>
      <webElementGuid>62097575-8dea-471a-a749-458713a4f928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_column</value>
      <webElementGuid>d60996da-8b96-4919-8c6f-e19952c5c516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_button_container&quot;)</value>
      <webElementGuid>7ee0f598-b293-4eb0-8dbd-e6d9a06f5987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login_button_container']</value>
      <webElementGuid>f9cfb21e-7ef4-4f4a-8061-47ff06fc5d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>65fd357e-139b-4633-a410-4072c9c1d6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login_button_container']</value>
      <webElementGuid>ea8ca72e-7f12-4b6d-9fcc-46af6fcd8023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
