<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divlogin_button_container</name>
   <tag></tag>
   <elementGuidId>d6eae766-ac84-4e9a-bdb1-d8596f05fe94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_button_container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_button_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>332da185-1408-4770-9593-26291762338c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_button_container</value>
      <webElementGuid>31b41c6b-a2fe-43df-a100-fd8ee31e82a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_column</value>
      <webElementGuid>5f99d6fb-0ead-4fa2-9e5e-be0a4c6fbf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_button_container&quot;)</value>
      <webElementGuid>bdbfec85-eca1-44f4-b1db-b6815955e326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login_button_container']</value>
      <webElementGuid>967b12b5-2611-4cde-a2b4-62ebacbce7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>0b2b0105-1c35-43a6-9c3b-e3e435da380a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login_button_container']</value>
      <webElementGuid>de5582cf-954e-4cf4-b9a8-fe7d7014c46b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
