<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CHECKOUT</name>
   <tag></tag>
   <elementGuidId>5549a956-f53f-489e-a273-86e05601539e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart_contents_container']/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn_action.checkout_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e611f80-edf9-4175-845b-686e5dbd47da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_action checkout_button</value>
      <webElementGuid>b46b2d42-81c9-491e-8078-698fa2577054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./checkout-step-one.html</value>
      <webElementGuid>363b0ca4-b0bd-4b9b-9062-5ed533c8eb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT</value>
      <webElementGuid>2f357232-b5d8-48f9-9123-b7908cc3cded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_contents_container&quot;)/div[1]/div[@class=&quot;cart_footer&quot;]/a[@class=&quot;btn_action checkout_button&quot;]</value>
      <webElementGuid>4d75d4d5-68b9-46e1-9519-94f2fe169cfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart_contents_container']/div/div[2]/a[2]</value>
      <webElementGuid>b0dea75a-eb04-417b-b776-81742943ee2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CHECKOUT')]</value>
      <webElementGuid>44d43714-baec-4901-ad90-e43c2386162b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './checkout-step-one.html')]</value>
      <webElementGuid>128ea2bd-4097-44d0-a1df-f42d2295ce70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>f5f6f0ba-a60e-4699-a38b-b691b5408a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './checkout-step-one.html' and (text() = 'CHECKOUT' or . = 'CHECKOUT')]</value>
      <webElementGuid>ca2d16e0-93f9-42eb-a7b7-f931bb807607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
