<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_footer_robot</name>
   <tag></tag>
   <elementGuidId>06e7c81c-7d3d-4739-bed3-7bde69806ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.footer_robot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>253248fd-cfb8-4308-bcb9-95821cb7cab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_robot</value>
      <webElementGuid>d4b12288-e99a-4aa7-b622-73abe2b12e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/SwagBot_Footer_graphic.png</value>
      <webElementGuid>c132a519-f765-455b-9e5b-34bb6f07b34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/footer[@class=&quot;footer&quot;]/img[@class=&quot;footer_robot&quot;]</value>
      <webElementGuid>10e9d76d-94c7-4b75-95c0-a9977cb76c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>852c2f90-42c2-4e00-8ec7-752a5a5812ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/SwagBot_Footer_graphic.png']</value>
      <webElementGuid>e5d3807b-2292-4791-b2a9-ab19eb22a150</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
